dbt_project:
  outputs:
    dev:
      job_execution_timeout_seconds: 300
      job_retries: 1
      threads: 1
      type: teradata
      host: devtools-test-25wbjoteev9ujvxw.env.clearscape.teradata.com
      schema: ecommerce_demo
      tmode: ANSI
      logmech: TD2
      user: demo_user
      password: Devtools@123
  target: dev

  
